# Generated by Django 3.1.7 on 2021-05-04 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PF_Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=200)),
                ('ages', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(blank=True, choices=[(1, 'female'), (0, 'male')], default=0, max_length=200)),
                ('smoke', models.CharField(blank=True, choices=[(0, 'Never smoking'), (11, 'Ex-smoke'), (10, 'Currently smoke')], default=0, max_length=200)),
                ('scan_img', models.ImageField(null=True, upload_to='')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
