# Generated by Django 3.1.7 on 2021-05-05 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ages', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(blank=True, choices=[(1, 'female'), (0, 'male')], default=0, max_length=200)),
                ('smoke', models.CharField(blank=True, choices=[(0, 'Never smoking'), (11, 'Ex-smoke'), (10, 'Currently smoke')], default=0, max_length=200)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPatientImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('ppatient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfds.ppatient')),
            ],
        ),
        migrations.DeleteModel(
            name='PF_Patient',
        ),
    ]
