# Generated by Django 3.1.7 on 2021-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfds', '0003_auto_20210505_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppatient',
            name='gender',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='ppatient',
            name='smoke',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
