# Generated by Django 3.1.7 on 2021-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfds', '0008_auto_20210509_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppatient',
            name='percent',
            field=models.FloatField(default=100, max_length=4),
        ),
    ]
